### ISSUE TITLE
과제 코드 리뷰

### ISSUE THREAD

**Issue by Doridori7** [eliotjang/tower-defense-game-project#70]
안녕하세요! 이번에 타워 디펜스 게임 서버 프로젝트 수행하시느라 대단히 고생이 많으셨습니다.

간단하게, 코드 리뷰를 해보도록 하겠습니다.

1.
game.handler.js에서 gameEnd 함수에 사용하지 않는 변수들을 참조하실 이유는 없어보입니다.
monster, baseHp, monsterSpawnInterval와 같은 것들입니다.

2.
const maxPossibleSpawn = elapsedTime / game.data.monsterSpawnInterval; 과 같은 코드는
게임 기획에 따라서는 유동적으로 monsterSpawnInterval에 생각한 몬스터 수보다 더 많은 몬스터가 나올 수도 있기 때문에 조심하셔야 합니다!
(예를 들어서, monsterSpawnInterval 타이머를 공유받지 않는 별도의 독립적 몬스터 스폰)

3.
patchGameDataEx 함수의 경우엔 트랜잭션도 적용하시고 나름 신경을 많이 쓰신 것 같습니다.
다만, 이 함수가 다른 유저들로 인해 내 데이터가 침범이 될 가능성이 많을지 생각을 해보면 좋겠습니다.
세션 관리만 올바르게 해놓으셨다면 UUID는 유저당 유일할 것이고 그렇게 되면 동일한 크리티컬 섹션을 접근할 일이 없습니다.

트랜잭션을 사용하는 주된 이유는 여러 명령을 원자적으로 실행하여 중간에 다른 변경이 발생하지 않도록 하는 것이죠.
따라서, 키가 겹치지 않으면 트랜잭션을 사용하지 않으시는 것이 성능적으론 이득입니다.

4.
이외에는 스테이지 상승 및 기타 게임 로직들 처리를 잘 해주셨습니다! 고생 많으셨습니다!

**Comment by eliotjang** [comment]
네 코드 리뷰 확인했습니다.
피드백 감사합니다!
